apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AzzouzCherif/gitops-demo.git'
    targetRevision: main
    path: apps/frontend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AzzouzCherif/gitops-demo.git'
    targetRevision: main
    path: apps/backend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AzzouzCherif/gitops-demo.git'
    targetRevision: main
    path: apps/frontend/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AzzouzCherif/gitops-demo.git'
    targetRevision: main
    path: apps/backend/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: backend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.0
    helm:
      releaseName: monitoring
      values: |
        grafana:
          adminPassword: admin
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.company.local
            tls:
              - secretName: company-local-tls-secret
                hosts:
                  - grafana.company.local
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.company.local
            tls:
              - secretName: company-local-tls-secret
                hosts:
                  - prometheus.company.local
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

